service: madhouse-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  vpc:
    securityGroupIds:
      - sg-07eb9a1adc283a497
    subnetIds:
      - subnet-0d8399bd43aef158a
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    LNBIT_URL: ${env:LNBIT_URL}
    LNBIT_API_KEY: ${env:LNBIT_API_KEY}
    LNBIT_USERNAME: ${env:LNBIT_USERNAME}
    LNBIT_PASS: ${env:LNBIT_PASS}
    LNBIT_URL_2: ${env:LNBIT_URL_2}
    LNBIT_API_KEY_2: ${env:LNBIT_API_KEY_2}
    LNBIT_USERNAME_2: ${env:LNBIT_USERNAME_2}
    LNBIT_PASS_2: ${env:LNBIT_PASS_2}
    SPEND_LNBIT_DB_HOST: ${env:SPEND_LNBIT_DB_HOST}
    SPEND_LNBIT_DB_USER: ${env:SPEND_LNBIT_DB_USER}
    SPEND_LNBIT_DB_PASSWORD: ${env:SPEND_LNBIT_DB_PASSWORD}
    SPEND_LNBIT_DB_NAME: ${env:SPEND_LNBIT_DB_NAME}
    SPLIT_PAYMENT_ADDRESS: ${env:SPLIT_PAYMENT_ADDRESS}
    SPLIT_PAYMENT_PERCENTAGE: ${env:SPLIT_PAYMENT_PERCENTAGE}
    PASSNINJA_ACCOUNTI_ID: ${env:PASSNINJA_ACCOUNTI_ID}
    PASSNINJA_API_KEY: ${env:PASSNINJA_API_KEY}
    PASSNINJA_CARD_APPLE_PAY: ${env:PASSNINJA_CARD_APPLE_PAY}
    PASSNINJA_CARD_GOOGLE_PAY: ${env:PASSNINJA_CARD_GOOGLE_PAY}
    NODE_OPTIONS: --enable-source-maps

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:ListTargetsByRule
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:AddPermission
            - lambda:RemovePermission
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  addlnbitUser:
    timeout: 900
    handler: handler.addlnbitUser
    events:
      - httpApi:
          path: /api/v1/addlnbitUser
          method: POST
          cors: true
  createUser:
    timeout: 900
    handler: handler.createUser
    events:
      - httpApi:
          path: /api/v1/createUser
          method: POST
          cors: true
  updtUser:
    timeout: 900
    handler: handler.updtUser
    events:
      - httpApi:
          path: /api/v1/updtUser
          method: POST
          cors: true
  getBitcoinWallet:
    timeout: 900
    handler: handler.getBitcoinWallet
    events:
      - httpApi:
          path: /api/v1/getBitcoinWallet
          method: POST
          cors: true
  testlnbit:
    timeout: 900
    handler: handler.testlnbit
    events:
      - httpApi:
          path: /api/v1/testlnbit
          method: POST
          cors: true
  testlnbit1:
    timeout: 900
    handler: handler.testlnbit1
    events:
      - httpApi:
          path: /api/v1/testlnbit1
          method: POST
          cors: true
  updateLnAddress:
    timeout: 900
    handler: handler.updateLnAddress
    events:
      - httpApi:
          path: /api/v1/updt-lnaddress
          method: POST
          cors: true
  payTposInvoice:
    timeout: 900
    handler: handler.payTposInvoice
  createTposIdInvoice:
    timeout: 900
    handler: handler.createTposIdInvoice
  getTposTrxn:
    timeout: 900
    handler: handler.getTposTrxn
  getUser:
    timeout: 900
    handler: handler.getUser

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - .git/**
    - .vscode/**
    - .test/**
    - node_modules/aws-sdk/**

