service: madhouse-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    LNBIT_URL: ${env:LNBIT_URL}
    LNBIT_API_KEY: ${env:LNBIT_API_KEY}
    LNBIT_USERNAME: ${env:LNBIT_USERNAME}
    LNBIT_PASS: ${env:LNBIT_PASS}
    LNBIT_URL_2: ${env:LNBIT_URL}
    LNBIT_API_KEY_2: ${env:LNBIT_API_KEY_2}
    LNBIT_USERNAME_2: ${env:LNBIT_USERNAME_2}
    LNBIT_PASS_2: ${env:LNBIT_PASS_2}
    SPEND_LNBIT_DB_HOST: ${env:SPEND_LNBIT_DB_HOST}
    SPEND_LNBIT_DB_USER: ${env:SPEND_LNBIT_DB_USER}
    SPEND_LNBIT_DB_PASSWORD: ${env:SPEND_LNBIT_DB_PASSWORD}
    SPEND_LNBIT_DB_NAME: ${env:SPEND_LNBIT_DB_NAME}
    NODE_OPTIONS: --enable-source-maps

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:ListTargetsByRule
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:AddPermission
            - lambda:RemovePermission
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  addlnbitUser:
    timeout: 900
    handler: handler.addlnbitUser
    events:
      - httpApi:
          path: /api/v1/addlnbitUser
          method: POST
          cors: true
 
plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - .git/**
    - .vscode/**
    - .test/**
    - node_modules/aws-sdk/**

