service: madhouse-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_OPTIONS: --enable-source-maps
   # CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Your Signing Profile ARN stored as secret

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:ListTargetsByRule
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:AddPermission
            - lambda:RemovePermission
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:

  requestQuote:
    timeout: 900
    memorySize: 2048
    handler: handler.requestQuote
    #environment:
    #  CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /api/v1/requestQuote
          method: POST
          cors: true
          
  createFixedShift:
    timeout: 900
    memorySize: 2048
    handler: handler.createFixedShift
    #environment:
    #  CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /api/v1/createFixedShift
          method: POST
          cors: true

  liquidSwap:
    timeout: 900
    memorySize: 2048
    handler: handler.liquidSwap
    #environment:
    #  CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /api/v1/liquidSwap
          method: POST
          cors: true 
          
plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'external/**'
    - '!*.test.js'
    - '**/*'
