name: Deploy main to production

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
   # - name: Build
   #   run: make build
    - name: Install npm dependencies
      run: npm install
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage production
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }} 
        CODE_SIGNING_PROFILE_ARN: ${{ secrets.CODE_SIGNING_PROFILE_ARN }} 
